language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t palo2332palo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true palo2332palo/docker-react npm run test -- --coverage
  